config/routes.rb
Politibuy::Application.routes.draw do

  authenticated :user do
    root :to => "campaigns#index"
  end

  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  
  match 'users/unzip' => "users#unzip_code", :via => :get
  
  resources :users, :only => [:show, :index] do
    get 'invite', :on => :member
  end
  
  resources :campaigns do
    resources :updates
    resources :pledges
    resources :key_policy_makers
    resources :beneficiaries
  end

  resources :policy_makers
  resources :vehicles
  
  match "admin" => "admin#index"
  match "admin/campaigns" => "admin#campaigns"
  
  match "about" => "welcome#about"
  match "terms" => "welcome#terms"
  match "privacy" => "welcome#privacy"
  match "ethics" => "welcome#ethics"

  

  root :to => "welcome#index"

end

app/views/admin/_tools.html.erb
<h4 class="campaign-show-other-campaigns">Admin Tools:</h4>
<% unless @campaign.nil? %>
<%= link_to "Edit Campaign", edit_campaign_path(@campaign) %> |
<% end %>
<%= link_to "Users", admin_path %> | <%= link_to "Campaigns", admin_campaigns_path %>

app/views/admin/campaigns.html.erb
<div id="majority-left-wrapper">
<h1 id="campaigns-index">Campaigns (<%= @campaigns.count %>)</h1>
<table class="admin-table">
  <tr class="admin-table">
    <th class="admin-table">Campaign</th>
    <th class="admin-actions">Actions</th>
  </tr>
  <% @campaigns.each_with_index do |c, i| %>
  <tr class="admin-table <%= i.odd? ? "odd-row": ""%>">
    <td class="admin-table"><%= truncate(c.title, :length => 40) %></td>
    <td class="admin-actions">
      <%= link_to "show", c %> | <%= link_to "edit", edit_campaign_path(c) %>
    </td>
  </tr>
  <% end %>
</table>
<%= link_to "Create Campaign", new_campaign_path %>
</div>
<div id="minority-right-wrapper">
  <%= render "tools" %>
</div>

app/views/admin/index.html.erb
<div id="majority-left-wrapper">
<h1 id="campaigns-index">Users (<%= @users.count %>)</h1>
<p>
  Send Bulk Invitations:
  <%= link_to "10 &#183;".html_safe, bulk_invite_path(:quantity => '10'), data: { confirm: 'Are you sure? This will email a bunch of people.' } %>
  <%= link_to "50 &#183;".html_safe, bulk_invite_path(:quantity => '50'), data: { confirm: 'Are you sure? This will email a bunch of people.' } %>
  <%= link_to "100 &#183;".html_safe, bulk_invite_path(:quantity => '100'), data: { confirm: 'Are you sure? This will email a bunch of people.' } %>
  <%= link_to "500 &#183;".html_safe, bulk_invite_path(:quantity => '500'), data: { confirm: 'Are you sure? This will email a bunch of people.' } %>
  <%= link_to "1000", bulk_invite_path(:quantity => '1000'), data: { confirm: 'Are you sure? This will email a bunch of people.' } %>
</p>
<table class="admin-table">
  <tr class="admin-table">
    <th class="admin-table">Email</th>
    <th class="admin-actions">Actions</th>
  </tr>
  <% @users.each_with_index do |user, i| %>
  <tr class="admin-table <%= i.odd? ? "odd-row": ""%>">
    <td class="admin-table"><%= user.email %></td>
    <td class="admin-actions">
      <%= (user.confirmation_token.nil? ? (link_to "send invitation", invite_user_path(user)) : (link_to "resend", invite_user_path(user))) unless user.confirmed_at %>
<%
=begin%>
      <% if not user.confirmed_at %>
        |
      <% end %> 
      <%= link_to "show", user %> 
<%
=end
%>
      </td>
  </tr>
  <% end %>
</table>
</div>
<div id="minority-right-wrapper">
  <%= render "tools" %>
</div>