config/routes.rb
Politibuy::Application.routes.draw do

  authenticated :user do
    root :to => "campaigns#index"
  end

  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  
  match 'users/unzip' => "users#unzip_code", :via => :get
  
  resources :users, :only => [:show, :index] do
    get 'invite', :on => :member
  end
  
  resources :campaigns do
    resources :updates
    resources :pledges
    resources :key_policy_makers
    resources :beneficiaries
  end

  resources :policy_makers
  resources :vehicles
  
  match "admin" => "admin#index"
  match "admin/campaigns" => "admin#campaigns"
  
  match "about" => "welcome#about"
  match "terms" => "welcome#terms"
  match "privacy" => "welcome#privacy"
  match "ethics" => "welcome#ethics"

  

  root :to => "welcome#index"

end

app/models/key_policy_maker.rb
class KeyPolicyMaker < ActiveRecord::Base
  attr_accessible :reason, :campaign_id, :policy_maker_id
  belongs_to :campaign
  belongs_to :policy_maker
end

app/controllers/key_policy_makers_controller.rb
class KeyPolicyMakersController < ApplicationController
  # GET /key_policy_makers
  # GET /key_policy_makers.json
  def index
    @campaigns = Campaign.all
    @campaign = Campaign.find(params[:campaign_id])
    @key_policy_makers = @campaign.key_policy_makers
    if user_signed_in? and @campaign.users.include? current_user
      @user_pledge = current_user.pledges.where(:campaign_id => @campaign.id).first
    else
      @user_pledge = false
    end
  end

  # GET /key_policy_makers/1
  # GET /key_policy_makers/1.json
  def show
    authenticate_user!
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    
    @key_policy_maker = KeyPolicyMaker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @key_policy_maker }
    end
  end

  # GET /key_policy_makers/new
  # GET /key_policy_makers/new.json
  def new
    authenticate_user!
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    
    @key_policy_maker = KeyPolicyMaker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @key_policy_maker }
    end
  end

  # GET /key_policy_makers/1/edit
  def edit
    authenticate_user!
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    
    @key_policy_maker = KeyPolicyMaker.find(params[:id])
  end

  # POST /key_policy_makers
  # POST /key_policy_makers.json
  def create
    authenticate_user!
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    
    @key_policy_maker = KeyPolicyMaker.new(params[:key_policy_maker])

    respond_to do |format|
      if @key_policy_maker.save
        format.html { redirect_to :back, notice: 'Key policy maker successfully created.' }
        format.json { render json: @key_policy_maker, status: :created, location: @key_policy_maker }
      else
        format.html { render action: "new" }
        format.json { render json: @key_policy_maker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /key_policy_makers/1
  # PUT /key_policy_makers/1.json
  def update
    authenticate_user!
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    
    @key_policy_maker = KeyPolicyMaker.find(params[:id])

    respond_to do |format|
      if @key_policy_maker.update_attributes(params[:key_policy_maker])
        format.html { redirect_to :back, notice: 'Key policy maker successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @key_policy_maker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /key_policy_makers/1
  # DELETE /key_policy_makers/1.json
  def destroy
    authenticate_user!
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    
    @key_policy_maker = KeyPolicyMaker.find(params[:id])
    @key_policy_maker.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/helpers/key_policy_makers_helper.rb
module KeyPolicyMakersHelper
end

app/views/key_policy_makers/_form.html.erb
<%= form_for(@key_policy_maker) do |f| %>
  <% if @key_policy_maker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@key_policy_maker.errors.count, "error") %> prohibited this key_policy_maker from being saved:</h2>

      <ul>
      <% @key_policy_maker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reason %><br />
    <%= f.text_field :reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/key_policy_makers/edit.html.erb
<h1>Editing key_policy_maker</h1>

<%= render 'form' %>

<%= link_to 'Show', @key_policy_maker %> |
<%= link_to 'Back', key_policy_makers_path %>

app/views/key_policy_makers/index.html.erb
<div id="majority-left-wrapper">
  <a href="#top"></a>
  <h1 class="campaign-show-title"><%= @campaign.title %></h1>
  
  <%= link_to "Back to Campaign", campaign_path(@campaign), :class => "campaign-nav-link"%>
    
  <div class="campaign-show-pledge-banner-outer">
    <div class="campaign-show-pledge-banner-inner">
      <div class="campaign-show-amount-wrapper">
        <h2 class="campaign-show-amount"><%= number_to_currency(@campaign.total_pledged) %></h2>
        <h4 class="campaign-show-subtext">pledged so far</h4>
      </div>
      <% if @user_pledge %>
        <%= link_to "Change Your Pledge", edit_campaign_pledge_path(@campaign, @user_pledge), :class => "landing-callaction-button", :id => "submit-pledge-link" %>
      <% else %>
        <%= link_to "Submit Your Pledge", new_campaign_pledge_path(@campaign), :class => "landing-callaction-button", :id => "submit-pledge-link" %>
      <% end %>
    </div>
  </div>
  
  <h2 class="campaign-show-objective">Campaign Objective:</h2>
  <p class="campaign-show-objective"><%= @campaign.objective %></p>
    
  <h2 class="campaign-section">Key Policy Makers:</h2>
  <ul class="key-policy-makers-index">
    <% @key_policy_makers.each do |kpm|%>
    <li class="key-policy-makers-index">
      <% if kpm.policy_maker.profile_image? %>
        <%= image_tag kpm.policy_maker.profile_image.url, :class => "key-policy-makers-index" %>
      <% else %>
        <%= image_tag "sam.jpeg", :class => "key-policy-makers-index" %>
      <% end %>
      <h3 class="key-policy-maker-name"><%= kpm.policy_maker.salutation + full_name(kpm.policy_maker.first_name, kpm.policy_maker.last_name) %></h3>
      <p class="key-policy-maker-subline"><%= kpm.policy_maker.party.capitalize + " from " + lengthen_state(kpm.policy_maker.home_state) %></p>
      <p class="key-policy-maker-bio">
        <%= kpm.policy_maker.bio %>
      </p>
      <h4 class="key-policy-maker-reason">How is <%= kpm.policy_maker.last_name %> important to this campaign?</h4>
      <p class="key-policy-maker-reason">
        <%= kpm.reason %>
      </p>
    </li>
    <% end %>
  </ul>
</div>


<div id="minority-right-wrapper">
  <div class="campaign-sidebar">
    <h4 class="campaign-show-other-campaigns">Live Campaigns:</h4>
    <ul class="campaign-show-other-campaigns">
      <% @campaigns.each do |c| %>
      <li class="campaign-show-other-campaign">
        <%= link_to c.title, campaign_path(c), :class => "other-campaigns-link"%>
      </li>
      <% end %>
    </ul>
    <% if user_signed_in? and can? :update, @campaign %>
      <%= render "admin/tools" %>
    <% end %>
  </div>
</div>

app/views/key_policy_makers/new.html.erb
<h1>New key_policy_maker</h1>

<%= render 'form' %>

<%= link_to 'Back', key_policy_makers_path %>

app/views/key_policy_makers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Reason:</b>
  <%= @key_policy_maker.reason %>
</p>


<%= link_to 'Edit', edit_key_policy_maker_path(@key_policy_maker) %> |
<%= link_to 'Back', key_policy_makers_path %>