config/routes.rb
Politibuy::Application.routes.draw do

  authenticated :user do
    root :to => "campaigns#index"
  end

  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  
  match 'users/unzip' => "users#unzip_code", :via => :get
  
  resources :users, :only => [:show, :index] do
    get 'invite', :on => :member
  end
  
  resources :campaigns do
    resources :updates
    resources :pledges
    resources :key_policy_makers
    resources :beneficiaries
  end

  resources :policy_makers
  resources :vehicles
  
  match "admin" => "admin#index"
  match "admin/campaigns" => "admin#campaigns"
  
  match "about" => "welcome#about"
  match "terms" => "welcome#terms"
  match "privacy" => "welcome#privacy"
  match "ethics" => "welcome#ethics"

  

  root :to => "welcome#index"

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :updates
  
  has_many :key_policy_makers
  has_many :policy_makers, :through => :key_policy_makers
  
  has_many :pledges
  has_many :users, :through => :pledges
  
  # beneficiaries are the PACS or other vehicles that recieve the pledge proceeds
  has_many :beneficiaries
  has_many :vehicles, :through => :beneficiaries
  
  attr_accessible :title, :description, :objective, :deadline, :live, :main_image
    
  has_attached_file :main_image,
    :storage => :s3,
    :bucket => ENV['S3_BUCKET'],
    :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET']
    },
    :s3_protocol => "https",
    :path => "campaigns/:attachment/:id/:style.:extension"
  
  def ordered_updates
    updates.sort! {|a,b| b.published_date <=> a.published_date}
  end

  def total_pledged
    pledges.reduce(0) do |sum, p|
      sum + p.amount
    end
  end
  
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  # remove before filter after closed beta
  before_filter :authenticate_user! 
  
  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.where(:live => true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @campaigns }
    end
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @campaigns = Campaign.where(:live => true)
    @campaign = Campaign.find(params[:id])
    @deadline = @campaign.deadline.utc
    if user_signed_in? and @campaign.users.include? current_user
      @user_pledge = current_user.pledges.where(:campaign_id => @campaign.id).first
    else
      @user_pledge = false
    end
    puts @user_pledge
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/new
  # GET /campaigns/new.json
  def new
    authenticate_user!
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    
    @campaign = Campaign.new
    @updating = false

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/1/edit
  def edit
    authenticate_user!
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    
    @campaign = Campaign.find(params[:id])
    
    @updating = true
    @new_update = @campaign.updates.build
    
    policy_makers = PolicyMaker.all
    @policy_makers_selections = []
    policy_makers.map do |pm|
      name = pm.last_name + ", " + pm.first_name
      @policy_makers_selections << [name, pm.id]
    end
    
    vehicles = Vehicle.all
    @vehicle_selections = []
    vehicles.map do |v|
      name = v.name
      @vehicle_selections << [name, v.id]
    end
    
    @new_policy_maker = PolicyMaker.new
    @new_key_policy_maker = @campaign.key_policy_makers.build
    # KeyPolicyMaker.new
    
    @new_vehicle = Vehicle.new
    # @new_beneficiary = Beneficiary.new
    @new_beneficiary = @campaign.beneficiaries.build
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    authenticate_user!
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    
    @campaign = Campaign.new(params[:campaign])

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render json: @campaign, status: :created, location: @campaign }
      else
        format.html { render action: "new" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /campaigns/1
  # PUT /campaigns/1.json
  def update
    authenticate_user!
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    
    @campaign = Campaign.find(params[:id])
    
    respond_to do |format|
      if @campaign.update_attributes(params[:campaign])
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    authenticate_user!
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    
    @campaign = Campaign.find(params[:id])
    
    @campaign.pledges.destroy_all
    @campaign.key_policy_makers.destroy_all
    @campaign.beneficiaries.destroy_all
    @campaign.updates.destroy_all
    
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to campaigns_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  
  def ensure_http(url)
    if url.include? "http"
      url
    else
      "http://"+url
    end
  end
  
end

app/views/campaigns/_beneficiary_form.html.erb
<div class="new-recipient-form-wrapper <%= index == @campaign.beneficiaries.count ? "last-recipient-form" : "" %>">
  
<%= form_for([@campaign,beneficiary], :html => {:class => "new-recipient-form"}) do |f| %>

  <%= f.hidden_field :campaign_id, :value => @campaign.id %>
  
  <% if beneficiary.vehicle.nil? %>
  <div class="field">
    <%= f.label :vehicle_id, "New Benefitting Vehicle", :class => "new-recipient-select-label" %>
    <% if @vehicle_selections.count > 0 %>
    <%= f.select :vehicle_id, @vehicle_selections %>
    <% else %>
    <span><i>(No vehicles found)</i></span>
    <% end %>
  </div>
  <% else %>
    <%= f.hidden_field :vehicle_id, :value => beneficiary.vehicle.id %>
    <p class="key-policy-maker-name"><%= beneficiary.vehicle.name %> 
      (<%= link_to 'Remove', [@campaign,beneficiary], method: :delete, data: { confirm: 'Are you sure?' } %> | 
      <%= link_to 'Edit Vehicle Info', edit_vehicle_path(beneficiary.vehicle, :breadcrumb_campaign_id => @campaign.id) %>)
    </p>
  <% end %>
  
  <div class="field new-recipient-reason">
    <%= f.label :reason %><br />
    <%= f.text_field :reason %>
  </div>
  
  <div class="actions">
    <%= f.submit "Add/Edit Beneficiary", :class => "create-recipient-submit" %>
  </div>
  
<% end %>
</div>

app/views/campaigns/_form.html.erb
<div class="edit-form-wrapper">
  <%= form_for(@campaign, :html => {:id => "campaign-form", :multipart => true}) do |f| %>
    <% if @campaign.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

        <ul>
        <% @campaign.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :objective %><br />
      <%= f.text_field :objective %>
    </div>
    
    <% if @campaign.main_image? %>
    <p class="current-image-label">Current Campaign Image</p>
    <%= image_tag @campaign.main_image.url, :class => "current-campaign-image" %>
    <div class="field">
      <%= f.label :main_image, "Change Campaign Image (570w x 200h)" %><br />
      <%= f.file_field :main_image %>
    </div>
    <% else %>
    <div class="field">
      <%= f.label :main_image, "Add Campaign Image (570w x 200h)" %><br />
      <%= f.file_field :main_image %>
    </div>
    <% end %>
    
    <div class="field">
      <%= f.label :deadline %> (UTC)<br />
      <%= f.datetime_select :deadline %>
    </div>
    <div class="field">
      <%= f.label :live %><br />
      <%= f.check_box :live %>
    </div>
    <div class="form-edit-actions">
      <% if @updating %>
        <%= f.submit "Update Campaign", :class => "edit-form-button" %>
        <%= link_to 'Destroy Campaign', @campaign, method: :delete, data: { confirm: 'Are you sure? This will destroy all associated records, including pledge information.' }, :class => "delete-button" %>
      <% else %>
        <%= f.submit "Create Campaign", :class => "edit-form-button" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/campaigns/_key_form.html.erb
<div class="new-recipient-form-wrapper <%= index == @campaign.key_policy_makers.count ? "last-recipient-form" : "" %>">
  
<%= form_for([@campaign,kpm], :html => {:class => "new-recipient-form"}) do |f| %>

  <%= f.hidden_field :campaign_id, :value => @campaign.id %>
  
  <% if kpm.policy_maker.nil? %>
  <div class="field">
    <%= f.label :policy_maker_id, "New Key Policy Maker", :class => "new-recipient-select-label" %>
    <% if @policy_makers_selections.count > 0 %>
    <%= f.select :policy_maker_id, @policy_makers_selections %>
    <% else %>
    <span><i>(No policy makers found)</i></span>
    <% end %>
  </div>  
  <% else %>
    <%= f.hidden_field :policy_maker_id, :value => kpm.policy_maker.id %>
    <p class="key-policy-maker-name"><%= full_name(kpm.policy_maker.first_name, kpm.policy_maker.last_name) %> 
      (<%= link_to 'Remove', [@campaign,kpm], method: :delete, data: { confirm: 'Are you sure?' } %> | 
      <%= link_to 'Edit Policy Maker', edit_policy_maker_path(kpm.policy_maker, :breadcrumb_campaign_id => @campaign.id) %>)
    </p>
  <% end %>
  
  <div class="field new-recipient-reason">
    <%= f.label :reason %><br />
    <%= f.text_field :reason %>
  </div>
  
  <div class="actions">
    <%= f.submit "Add/Edit Key Policy Maker", :class => "create-recipient-submit" %>
  </div>
  
<% end %>

</div>

app/views/campaigns/_policy_maker_form.html.erb
<div class="policy-maker-form-wrapper">

  <%= form_for(@new_policy_maker, :html => {:class => "policy-maker"}) do |f| %>
  <div class="policy-maker-form-col">
    <div class="field">
      <%= f.label :salutation %><br />
      <%= f.text_field :salutation %>
    </div>
    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :party_affiliation %><br />
      <%= f.select :party, party_affiliations %>
    </div>
    <div class="field">
      <%= f.label :home_state %><br />
      <%= f.select :home_state, us_states %>
    </div>
  </div>
  <div class="policy-maker-form-col">
    <div class="field">
      <%= f.label :bio %><br />
      <%= f.text_area :bio %>
    </div>
    <div class="field">
      <%= f.label :fund_vehicle %><br />
      <%= f.text_field :vehicle %>
    </div>
    <div class="field policy-maker-image-upload">
      <%= f.label :profile_image, "Profile Picture (120x120)" %><br />
      <%= f.file_field :profile_image %>
    </div>
  </div>
    <div class="actions">
      <%= f.submit "Create Policy Maker", :class => "create-policy-maker-button" %>
    </div>
  
  <% end %>
  
</div>

app/views/campaigns/_updates_form.html.erb
<div class="update-form-wrapper <%= index == @campaign.updates.count ? "last-update-form" : "" %>">
  
  <%= form_for([@campaign, update], :html => {:class => "update-form"}) do |f| %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :reference_url %><br />
      <%= f.text_field :reference_url %>
    </div>
    <div class="field">
      <%= f.label :long_preview %><br />
      <%= f.text_area :long_preview %>
    </div>
    <div class="field">
      <%= f.label :published_date %><br />
      <%= f.date_select :published_date %>
    </div>

    <%= f.submit "Add/Edit Update", :class => "edit-form-button" %>

  <% end %>
  
</div>

app/views/campaigns/_vehicle_form.html.erb
<div class="vehicle-form-wrapper">

  <%= form_for(@new_vehicle, :html => {:class => "vehicle"}) do |f| %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, :class => "vehicle-input" %>
    </div>
    <div class="field">
      <%= f.label :info_link %><br />
      <%= f.text_field :info_link, :class => "vehicle-input" %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description, :class => "vehicle-input" %>
    </div>
    <div class="field policy-maker-image-upload">
      <%= f.label :logo_image %><br />
      <%= f.file_field :logo_image %>
    </div>
  
    <div class="actions">
      <%= f.submit "Create Vehicle", :class => "create-vehicle-button" %>
    </div>
  
  <% end %>
  
</div>

app/views/campaigns/edit.html.erb
<div id="majority-left-wrapper">
  <h1 id="campaigns-index">Edit campaign</h1>
  <%= link_to "Show Campaign", @campaign, :id => "edit-campaign-top-view-link"%>
  <%= render 'form' %>
  
  <h2 class="campaign-edit">Add/Edit Key Policy Makers</h2>
    <% @campaign.key_policy_makers.each_with_index do |kpm, i| %>
    <%= render 'key_form', :kpm => kpm, :index => i %>
    <% end %>
  <p class="add-policy-maker-prompt">Need to add a policy maker to the list? Click <span id="policy-maker-form-show">here</span>.</p>
  <%= render 'policy_maker_form' %>

  <h2 class="campaign-edit">Add/Edit Benefitting Vehicles</h2>
  <% @campaign.beneficiaries.each_with_index do |b,i| %>
    <%= render 'beneficiary_form', :beneficiary => b, :index => i%>
  <% end %>
  <p class="add-policy-maker-prompt">Need to add a contribution vehicle to the list? Click <span id="vehicle-form-show">here</span>.</p>
  <%= render 'vehicle_form' %>  
  
  <h2 class="campaign-edit">Add/Edit News and Updates</h2>
  <% @campaign.updates.each_with_index do |u,i| %>
    <%= render 'updates_form', :update => u, :index => i %>
  <% end %>
</div>

app/views/campaigns/index.html.erb
<h1 id="campaigns-index">Active Campaigns</h1>
<% if user_signed_in? and can? :update, @campaign %>
<%= link_to "Create Campaign", new_campaign_path %>
<% end %>
<ul id="campaign-list">
  <% @campaigns.each do |campaign| %>
  <li class="campaign">
    <%= link_to campaign.title, campaign_path(campaign), :class => "campaign-title"%>
    <p class="campaign-description">
      <%= truncate(campaign.description, :length => 400) %>
    </p>
    <%= link_to campaign_path campaign do %>
    <div class="campaign-image-wrapper-outer">
      <div class="campaign-image-wrapper-inner">
        <%= image_tag campaign.main_image, :class => "campaign-index-image" %>
        <%= image_tag "campaign_ribbon.png", :class => "campaign-ribbon" %>
        <h3 class="campaign-pledge-ribbon-amount"><%= number_to_currency(campaign.total_pledged) %> pledged so far</h3>
      </div>
    </div>
    <% end %>
  </li>
  <% end %>
</ul>



























<%
=begin%>

<h1>Listing campaigns</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @campaigns.each do |campaign| %>
  <tr>
    <td><%= campaign.title %></td>
    <td><%= link_to 'Show', campaign %></td>
    <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
    <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Campaign', new_campaign_path %>

<%
=end
%>

app/views/campaigns/new.html.erb
<div id="majority-left-wrapper">
  <h1 id="campaigns-index">New campaign</h1>
  <%= link_to "Cancel", campaigns_path, :id => "edit-campaign-top-view-link"%>
  <%= render 'form' %>
</div>

app/views/campaigns/show.html.erb
<div id="slightly-more-left-wrapper">
  <a href="#top"></a>
  <h1 class="campaign-show-title"><%= @campaign.title %></h1>

  <!-- <h2 class="campaign-show-objective">Campaign Objective</h2> -->
  <p class="campaign-show-objective">Objective: <%= @campaign.objective %></p>
    
  <div class="campaign-main-image-wrapper">
    <% if @campaign.main_image %>
      <%= image_tag @campaign.main_image.url %>
    <% else %>
      <%= image_tag "coal_plant.jpeg"%>
    <% end %>
  </div>
<%
=begin%>
  <div class="campaign-image-recipient-wrapper">
    <div class="campaign-recipients-wrapper">
      <h3 class="campaign-subsection">Key Policy Makers</h3>
      <% fpm = @campaign.key_policy_makers[0] %>
      <% spm = @campaign.key_policy_makers[1] %>
      <% [fpm,spm].each do |kpm| %>
        <% if kpm %>
        <div class="campaign-recipient-wrapper">
          <h4 class="campaign-recipient-name"><%= full_name(kpm.policy_maker.first_name, kpm.policy_maker.last_name )%></h4>
          <p class="campaign-recipient-bio"><%= truncate(kpm.reason, :length => 95) %></p>
          <% if kpm.policy_maker.profile_image? %>
            <%= image_tag kpm.policy_maker.profile_image.url, :class => "campaign-recipient-image-small"%>
          <% else %>
            <%= image_tag "sam.jpeg", :class => "campaign-recipient-image-small"%>
          <% end %>
        </div>
        <% end %>
      <% end %>
      <%= link_to "See more info", campaign_key_policy_makers_path(@campaign), :class => "campaign-show-see-more-recipients"%>
    </div>
  </div>
<%
=end
%>

  
  <!-- <h2 class="campaign-section">Description</h2> -->
  <%= simple_format(@campaign.description, :class => "campaign-show-description") %>
  
  <h2 class="campaign-section">Where your money would go</h2>
  <ul class="campaign-beneficiaries">
    <% @campaign.beneficiaries.each do |b| %>
    <li class="campaign-beneficiaries">
      <% if b.vehicle.logo_image? %>
        <%= image_tag b.vehicle.logo_image.url, :class => "campaign-beneficiary-logo" %>
      <% else %>
        <%= image_tag "sam.jpeg", :class => "campaign-beneficiary-logo" %>
      <% end %>
      <h3 class="campaign-beneficiary-name"><%= link_to b.vehicle.name, ensure_http(b.vehicle.info_link), :target => "_blank", :class => "campaign-beneficiary-name" %></h3>
      <p class="campaign-beneficiary-description">
        <%= b.vehicle.description %>
      </p>
      <h4 class="campaign-beneficiary-reason">Why put money here?</h4>
      <p class="campaign-beneficiary-reason">
        <%= b.reason %>
      </p>
    </li>
    <% end %>
  </ul>
  
  <div class="campaign-updates-section">
    <h2 class="campaign-section">Campaign News and Updates</h2>
    <ul class="campaign-updates">
      <% @campaign.ordered_updates.each do |u| %>
      <li class="campaign-update">
        <%= link_to u.title, ensure_http(u.reference_url), :class => "campaign-update", :target => "_blank" %>
        <p class="campaign-update-preview">
          <span>
            <%= u.long_preview %>
          </span> 
          <span class="campaign-update-read-more"><%= link_to "read more", ensure_http(u.reference_url), :target => "_blank", :class => "campaign-update-read-more" %></span>
        </p>
        <p class="campaign-update-date campaign-update-date-month"><%= u.published_date.strftime("%b")%></p>
        <p class="campaign-update-date campaign-update-date-day"><%= u.published_date.strftime("%d")%></p>
        <p class="campaign-update-date campaign-update-date-year"><%= u.published_date.strftime("%Y")%></p>
      </li>
      <% end %>
    </ul>
  </div>
  
  <div class="campaign-bottom-action-links">
    <%= link_to "back to all campaigns", campaigns_path, :class => "campaign-bottom-links", :id => "return-to-campaigns" %>
    <%= link_to "back to top", "#top", :class => "campaign-bottom-links", :id => "back-to-top" %>
<%
=begin%>
    <%= link_to "like", "", :class => "campaign-bottom-links", :id => "like-bottom" %>
    <%= link_to "tweet", "", :class => "campaign-bottom-links", :id => "tweet-bottom" %>
    <%= link_to "pledge", "", :class => "campaign-bottom-links", :id => "pledge-bottom" %>
<%
=end
%>
  </div>
  
</div>


<div id="slightly-less-right-wrapper">
  <div class="campaign-sidebar">
    <div class="campaign-show-pledge-banner-outer">
      <div class="campaign-show-pledge-banner-inner">
        <div class="campaign-show-amount-wrapper">
          <h2 class="campaign-show-amount"><%= number_to_currency(@campaign.total_pledged) %></h2>
          <h4 class="campaign-show-subtext">pledged so far</h4>
        </div>
        <% if @user_pledge %>
          <%= link_to "Change Your Pledge", edit_campaign_pledge_path(@campaign, @user_pledge), :class => "landing-callaction-button", :id => "submit-pledge-link" %>
        <% else %>
          <%= link_to "Submit Your Pledge", new_campaign_pledge_path(@campaign), :class => "landing-callaction-button", :id => "submit-pledge-link" %>
        <% end %>
        <div class="campaign-deadline-backdrop"></div>
        <h4 class="campaign-deadling-header">Policy Deadline:</h4>
        <h1 id="countdown-timer" class="campaign-deadline"></h1>
      </div>
    </div>
    
    <div class="campaign-participants-section">
      <h2 class="campaign-section">Join <%= @campaign.pledges.count %> other Americans:</h2>
      <ul class="campaign-participants-wrapper">
        <% @campaign.pledges.each_with_index do |pledge,i| %>
        <li class="participant-wrapper <%= i%6 == 5 ? "edge-participant" : "" %>">
          <div class="participant-image-wrapper">
          <% if pledge.user.profile_image? %>
            <%= image_tag pledge.user.profile_image.url, :class => "participant-pic" %>
          <% else %>
            <%= image_tag "sam.jpg", :class => "participant-pic" %>
          <% end %>
          </div>
          <div class="participant-amount-wrapper"></div>
          <h4 class="participant-amount"><%= number_to_currency(pledge.amount, :precision => 0) %></h4>
        </li>
        <% end %>
      </ul>
    </div>
    
    <h4 class="campaign-show-other-campaigns">All Live Campaigns:</h4>
    <ul class="campaign-show-other-campaigns">
      <% @campaigns.each do |c| %>
      <li class="campaign-show-other-campaign">
        <%= link_to c.title, campaign_path(c), :class => "other-campaigns-link"%>
      </li>
      <% end %>
    </ul>

    <% if user_signed_in? and can? :update, @campaign %>
      <%= render "admin/tools" %>
    <% end %>
  </div>
</div>


<script>
var deadlineDate = new Date("<%= @deadline %>");
// countdown from http://www.webmuse.co.uk/projects/jcountdown-jquery-plugin/
$(document).ready(function(){

  $("#countdown-timer").countdown({
      "date" : deadlineDate,
      "offset" : -4,
      "htmlTemplate": "%d days, %h:%i:%s",
      "leadingZero":true,
      "onComplete" : function(event) {
          $(this).html("Campaign Completed");
      }
  });

});
</script>