config/routes.rb
Politibuy::Application.routes.draw do

  authenticated :user do
    root :to => "campaigns#index"
  end

  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  
  match 'users/unzip' => "users#unzip_code", :via => :get
  
  resources :users, :only => [:show, :index] do
    get 'invite', :on => :member
  end
  
  resources :campaigns do
    resources :updates
    resources :pledges
    resources :key_policy_makers
    resources :beneficiaries
  end

  resources :policy_makers
  resources :vehicles
  
  match "admin" => "admin#index"
  match "admin/campaigns" => "admin#campaigns"
  
  match "about" => "welcome#about"
  match "terms" => "welcome#terms"
  match "privacy" => "welcome#privacy"
  match "ethics" => "welcome#ethics"

  

  root :to => "welcome#index"

end

app/views/layouts/_flash.html.erb
<% unless flash.empty? %>
<div id="flash-wrapper-outer">
<% if flash[:notice]  %>
  <div class="flash-wrapper-inner">
    <%= image_tag "checkmark.png", :class => "notice" %>
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="flash-wrapper-inner">
    <%= image_tag "alert.png", :class => "notice" %>
    <p class="alert"><%= alert %></p>
  </div>
<% end %>
</div>
<% end %>

app/views/layouts/_right_sidebar.html.erb
<h3 class="about-right">Blog Posts</h3>
<ul class="about-blog-entry">
  <li class="about-blog-entry">
    <p class="about-blog-entry-date">10/4/2012</p>
    <%= link_to "Pharma lobbying = high drug prices and taxpayer waste", "http://blog.politibuy.org/pharma-lobbying-prices/", :class => "about-blog-entry", :target => "_blank" %>
  </li>
  <li class="about-blog-entry">
    <p class="about-blog-entry-date">10/3/2012</p>
    <%= link_to "Bank lobbying and the financial crisis", "http://blog.politibuy.org/banking-lobbying-crisis/", :class => "about-blog-entry", :target => "_blank" %>
  </li>
  <li class="about-blog-entry">
    <p class="about-blog-entry-date">10/2/2012</p>
    <%= link_to "Introducing GetItPassed.org!", "http://blog.politibuy.org/intro/", :class => "about-blog-entry", :target => "_blank" %>
  </li>
</ul>
<h3 class="about-right">Twitter Feed</h3>
<div class="twitter-feed"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GetItPassed - Motivating politicians to take action</title>
  <meta property="og:title" content="GetItPassed - Motivating politicians to take action" />
  <meta property="og:url" content="https://www.getitpassed.org" />
  <meta property="og:image" content="https://www.getitpassed.org/assets/politibuy_med.jpg"/>
  <meta property="og:description" content="Money gets your voice heard in Washington. What would you pay to see government get something done?" />
  <meta property="fb:admins" content="222984" />
  <meta property="og:type" content="website" />
    
  <%= stylesheet_link_tag    "application", :media => "all" %>
  
  <% if @stripe_needed %>
  <%= javascript_include_tag "https://js.stripe.com/v1/" %>
  <script>
    var politibuyPaymentNeeded = true;
  </script>
  <% else%>
  <script>
    var politibuyPaymentNeeded = false;
  </script>
  <% end %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-35202970-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>
<body>
  <div id="all-content-outer">
    <div id="all-content-inner">
      <div id="header">
        <%= link_to((image_tag "getitpassed.png", :id => "main-logo"), root_path) %>

        <div id="login-links">
<%
=begin%>          
          <%= link_to "Browse Campaigns", campaigns_path, :class => "header-links" %>
          <span class="divider-star"><%= image_tag "small_star.png"%></span>
<%
=end
%>
          <% if user_signed_in? %>
          <%= link_to "Browse Campaigns", campaigns_path, :class => "header-links" %>
          <span class="divider-star"><%= image_tag "small_star.png"%></span>
          <%= link_to "Account", edit_user_registration_path, :class => "header-links" %>
          <span class="divider-star"><%= image_tag "small_star.png"%></span>
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "header-links "%>
          <% else %>
          <%= link_to "About", about_path, :class => "header-links "%>
          <span class="divider-star"><%= image_tag "small_star.png"%></span>          
          <%= link_to "Sign In", new_user_session_path, :class => "header-links" %>
<%
=begin%>          
          <span class="divider-star"><%= image_tag "small_star.png"%></span>
          <%= link_to "Register", new_user_registration_path, :class => "header-links" %>
<%
=end
%>
          <% end %>
        </div>

      </div>
      
      <%= render :partial => 'layouts/flash', :locals => { :flash => flash } %>

      <%= yield %>
    </div>
    <div id="footer-outer">
      <div id="footer-inner">
        <div id="footer-social-media-buttons">
          <div id="footer-tweet">
            <a class="twitter-share-button" data-count="horizontal" data-text="I joined the revolution!" data-url="http://www.getitpassed.org/" data-via="getitpassed" data-related="lessig" href="https://twitter.com/share"></a>
          </div>
          <div id="fb-like-footer" class="fb-like" data-href="https://www.getitpassed.org/" data-layout="button_count" data-send="false" data-show-faces="false" data-width="90"></div><br/>
          <div id="gplus-footer" class="g-plusone" data-annotation="inline" data-href="http://www.getitpassed.org/" data-size="medium" data-width="120"></div>
        </div>

        <div id="footer-links">
          <span class="divider-star"><%= image_tag "small_star.png"%></span>
           <%= link_to "About", about_path, :class => "footer-link", :id => "footer-about-link" %>          
          <span class="divider-star"><%= image_tag "small_star.png"%></span>
          <%= link_to "Blog", "http://blog.politibuy.org", :class => "footer-link", :id => "footer-blog-link", :target => "_blank" %>
          <span class="divider-star"><%= image_tag "small_star.png"%></span>
          <%= link_to "Terms", terms_path, :class => "footer-link", :id => "footer-terms-link" %>
          <span class="divider-star"><%= image_tag "small_star.png"%></span>
          <%= link_to "Privacy", privacy_path, :class => "footer-link", :id => "footer-share-link" %>
          <span class="divider-star"><%= image_tag "small_star.png"%></span>
          <%= link_to "Ethics", ethics_path, :class => "footer-link", :id => "footer-share-link" %>
          <span class="divider-star"><%= image_tag "small_star.png"%></span>
        </div>
        
        <div id="footer-legal-disclaimers">
          <p id="copyright">Copyright © 2012 GetItPassed.org</p>
          <p id="affiliation">Paid for by GetItPassed.org. Not authorized by any candidate or candidate's committee.</p>
        </div>
    
      </div>
    </div>
  </div>
  <div id="header-blue" class="header-bar"></div>
  <div id="header-red-top" class="header-bar"></div>
  <div id="header-red-bottom" class="header-bar"></div>

<!-- landing page content  -->
<% if request.fullpath == "/" and not user_signed_in? %>
  <div id="landing-image-outer">
    <%= image_tag "landing_image.jpg", :id => "landing-image" %>
    <div id="landing-image-text">
      <%= image_tag "intro_text.png", :id => "landing-intro-text" %>
    </div>
  </div>
  
  <div id="landing-call-to-action-outer">
    <div id="landing-call-to-action-inner">      
    </div>
  </div>
  
  <div id="landing-how-works-outer">
    <div id="landing-how-works-inner">
      <div class="landing-how-step">
        <h4 class="landing-how-step">Pick a campaign</h4>
        <p class="landing-how-step">Healthcare reform? Wasteful subsidies? Choose an issue where you'd like to see politicians take action.</p>
      </div>
      <div class="landing-how-step">
        <h4 class="landing-how-step">Make a pledge</h4>
        <p class="landing-how-step">Make a monetary pledge to support legislators that vote for specific new laws or reforms. A large pool of pledges will incent politicians to get the job done.</p>
      </div>
      <div class="landing-how-step">
        <h4 class="landing-how-step">Only pay for results</h4>
        <p class="landing-how-step">If and only if the law passes, your money will be used to support legislators that made the law possible. If no law is passed, you keep 100% of your money!</p>
      </div>
    </div>
  </div>
<% end %>
<!-- end landing page content -->
</body>
</html>